# Generated by Django 6.1.1 on 2026-09-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('accessory', 'Accessory')], default='accessory', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='OLD-001', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
